ibm:
  mq:
    queueManager: QM1
    channel: SYSTEM.DEF.SVRCONN
    connName: localhost(1414)

logging:
  pattern:
    console: "%logger{36} - %msg%n"
  level:
    root: WARN
    com:
      ibm:
        mq:
          spring:
            boot: TRACE
